### ISSUE TITLE
`make diamond_collector_test` should set up a virtualenv

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/fullerite#266]
By default, running `make diamond_collector_test` (or, by extension, `make test`), fails, unless you create a virtualenv:

```
krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $ make diamond_collector_test
Failed to import module: testzookeeper. Traceback (most recent call last):
  File "src/diamond/test.py", line 261, in getCollectorTests
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/zookeeper/test/testzookeeper.py", line 9, in <module>
    from zookeeper import ZookeeperCollector
ImportError: cannot import name ZookeeperCollector

Failed to import module: test_scribe. Traceback (most recent call last):
  File "src/diamond/test.py", line 261, in getCollectorTests
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/scribe/test/test_scribe.py", line 8, in <module>
    from scribe import ScribeCollector
ImportError: cannot import name ScribeCollector

Failed to import module: testmesos. Traceback (most recent call last):
  File "src/diamond/test.py", line 261, in getCollectorTests
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mesos/test/testmesos.py", line 13, in <module>
    from mesos import MesosCollector
ImportError: cannot import name MesosCollector

..............FF.Unable to convert 277.0xs: unit xs
......................need more than 1 value to unpack
.need more than 1 value to unpack
.need more than 1 value to unpack
.......................................Unable to read JSON response.
Unable to retrieve MBean listing.
.......FFF...FFFFF...................Unable to parse response from elasticsearch as a json object
........................Couldnt parse json: No JSON object could be decoded
.....FFFFF.FFF..........EF.......................Cannot load json data: No JSON object could be decoded: line 1 column 0 (char 0)
..............GearmanCollector Error:
...Couldnt parse json: No JSON object could be decoded
...Unable to parse response from solr as a json object
....Unable to parse response from mx4j
.http://127.0.0.1:8082/path?template=identity: <urlopen error BOOM>
.......
======================================================================
ERROR: test_instance_names (testpgbouncer.TestPgbouncerCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/pgbouncer/test/testpgbouncer.py", line 72, in test_instance_names
    collector.collect()
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/pgbouncer/pgbouncer.py", line 93, in collect
    host, port, user, password).iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'

======================================================================
FAIL: test_instances (testslony.TestSlonyCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/slony/test/testslony.py", line 79, in test_instances
    self.assertPublished(publish, 'bar', 14)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: bar: actual number of calls 0, expected 1

======================================================================
FAIL: test_override_user_password_nodestr (testslony.TestSlonyCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/slony/test/testslony.py", line 108, in test_override_user_password_nodestr
    'postgres', '_postgres', '(.*)'
  File "/usr/lib/pymodules/python2.6/mock.py", line 880, in assert_any_call
    '%s call not found' % expected_string
AssertionError: _get_stats_by_database('localhost', 5432, 'postgres', 'postgres', 'postgres', '_postgres', '(.*)') call not found

======================================================================
FAIL: test_should_ignore_unneeded_collections (testmongodb.TestMongoDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 125, in test_should_ignore_unneeded_collections
    self.connection['db1'].collection_names.assert_called_once_with()
  File "/usr/lib/pymodules/python2.6/mock.py", line 834, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 2 times.

======================================================================
FAIL: test_should_ignore_unneeded_databases (testmongodb.TestMongoDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 106, in test_should_ignore_unneeded_databases
    assert call('baddb') not in self.connection.__getitem__.call_args_list
AssertionError

======================================================================
FAIL: test_should_publish_nested_keys_for_db_stats (testmongodb.TestMongoDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 68, in test_should_publish_nested_keys_for_db_stats
    self.connection['db1'].command.assert_called_once_with('dbStats')
  File "/usr/lib/pymodules/python2.6/mock.py", line 834, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 2 times.

======================================================================
FAIL: test_should_ignore_unneeded_collections (testmongodb.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 255, in test_should_ignore_unneeded_collections
    self.assertPublishedMany(publish_mock, metrics)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27017.databases.db1.collection1.key: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_ignore_unneeded_databases (testmongodb.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 226, in test_should_ignore_unneeded_databases
    assert call('baddb') not in self.connection.__getitem__.call_args_list
AssertionError

======================================================================
FAIL: test_should_publish_nested_keys_for_db_stats (testmongodb.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 195, in test_should_publish_nested_keys_for_db_stats
    self.assertPublishedMany(publish_mock, metrics)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27057.db_keys.db_nested_key: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_publish_nested_keys_for_server_stats (testmongodb.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 170, in test_should_publish_nested_keys_for_server_stats
    'localhost_27057.key': 2
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27017.more_keys.nested_key: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_publish_stats_with_long_type (testmongodb.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/mongodb/test/testmongodb.py", line 213, in test_should_publish_stats_with_long_type
    'localhost_27057.key': 2
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27057.more_keys: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_ignore_unneeded_collections (testtokumx.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 259, in test_should_ignore_unneeded_collections
    self.assertPublishedMany(publish_mock, metrics)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27017.databases.db1.collection1.key: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_ignore_unneeded_databases (testtokumx.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 229, in test_should_ignore_unneeded_databases
    assert call('baddb') not in self.connection.__getitem__.call_args_list
AssertionError

======================================================================
FAIL: test_should_publish_nested_keys_for_db_stats (testtokumx.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 198, in test_should_publish_nested_keys_for_db_stats
    self.assertPublishedMany(publish_mock, metrics)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27057.db_keys.db_nested_key: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_publish_nested_keys_for_server_stats (testtokumx.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 173, in test_should_publish_nested_keys_for_server_stats
    'localhost_27057.key': 2
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27017.more_keys.nested_key: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_publish_stats_with_long_type (testtokumx.TestMongoMultiHostDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 216, in test_should_publish_stats_with_long_type
    'localhost_27057.key': 2
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 184, in assertPublishedMany
    self.assertPublished(mock, key, value, expected_value)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/test.py", line 157, in assertPublished
    self.assertEqual(actual_value, expected_value, message)
AssertionError: localhost_27057.more_keys: actual number of calls 0, expected 1

======================================================================
FAIL: test_should_ignore_unneeded_collections (testtokumx.TestTokuMXCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 128, in test_should_ignore_unneeded_collections
    self.connection['db1'].collection_names.assert_called_once_with()
  File "/usr/lib/pymodules/python2.6/mock.py", line 834, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 2 times.

======================================================================
FAIL: test_should_ignore_unneeded_databases (testtokumx.TestTokuMXCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 108, in test_should_ignore_unneeded_databases
    assert call('baddb') not in self.connection.__getitem__.call_args_list
AssertionError

======================================================================
FAIL: test_should_publish_nested_keys_for_db_stats (testtokumx.TestTokuMXCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/tokumx/test/testtokumx.py", line 69, in test_should_publish_nested_keys_for_db_stats
    self.connection['db1'].command.assert_called_once_with('dbStats')
  File "/usr/lib/pymodules/python2.6/mock.py", line 834, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected to be called once. Called 2 times.

======================================================================
FAIL: test_override_user_password (testpgbouncer.TestPgbouncerCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/mock.py", line 1190, in patched
    return func(*args, **keywargs)
  File "/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/src/diamond/collectors/pgbouncer/test/testpgbouncer.py", line 100, in test_override_user_password
    '127.0.0.1', '6433', 'postgres', 'foobar')
  File "/usr/lib/pymodules/python2.6/mock.py", line 880, in assert_any_call
    '%s call not found' % expected_string
AssertionError: _get_stats_by_database('127.0.0.1', '6433', 'postgres', 'foobar') call not found

----------------------------------------------------------------------
Ran 222 tests in 2.744s

FAILED (failures=19, errors=1)
make: *** [diamond_collector_test] Error 1
krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $
```

```
krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...done.
krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $ . venv/bin/activate
(venv)krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $ pip install -r requirements-dev.txt
Downloading/unpacking configobj (from -r requirements-dev.txt (line 1))
  Downloading configobj-5.0.6.tar.gz
  Running setup.py (path:/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/venv/build/configobj/setup.py) egg_info for package configobj
Downloading/unpacking mock (from -r requirements-dev.txt (line 2))
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking six (from configobj->-r requirements-dev.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking funcsigs>=1 (from mock->-r requirements-dev.txt (line 2))
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Downloading/unpacking pbr>=0.11 (from mock->-r requirements-dev.txt (line 2))
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB): 96kB downloaded
Downloading/unpacking ordereddict (from funcsigs>=1->mock->-r requirements-dev.txt (line 2))
  Downloading ordereddict-1.1.tar.gz
  Running setup.py (path:/nail/home/krall/pg/go/src/github.com/Yelp/fullerite/venv/build/ordereddict/setup.py) egg_info for package ordereddict
Installing collected packages: configobj, mock, six, funcsigs, pbr, ordereddict
  Running setup.py install for configobj
  Running setup.py install for ordereddict
Successfully installed configobj mock six funcsigs pbr ordereddict
Cleaning up...
(venv)krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $ make diamond_collector_test
.................Unable to convert 277.0xs: unit xs
.......................need more than 1 value to unpack
.need more than 1 value to unpack
.need more than 1 value to unpack
.......................................Unable to read JSON response.
Unable to retrieve MBean listing.
.....................................Unable to parse response from elasticsearch as a json object
....................Unable to read JSON response: No JSON object could be decoded
.......Couldnt parse json: No JSON object could be decoded
.................................................Cannot load json data: No JSON object could be decoded
.................Couldnt parse json: No JSON object could be decoded
...Unable to parse response from solr as a json object
....Unable to parse response from mx4j
.http://127.0.0.1:8082/path?template=identity: <urlopen error BOOM>
.......
----------------------------------------------------------------------
Ran 226 tests in 2.570s

OK
(venv)krall@dev5-devc:~/pg/go/src/github.com/Yelp/fullerite (master) $
```

**Comment by gnufied** [comment]
The reason the test suite succeeds in virtualenv and fails without it is because - some of those tests flat out don't run if certain libraries (such as mongo-client drivers) are not present. So when a virtualenv is created - many of those Python libraries don't exist and those problematic tests don't fail. 

Most of the collectors that are failing - we aren't using, so I am thinking of further blacklisting them.

**Comment by EvanKrall** [comment]
Rather than skipping tests if certain modules aren't available, I think it would be better use a virtualenv to make sure those modules exist in the testing environment. This would also ensure that everybody is testing in a consistent environment.
