### ISSUE TITLE
Import errors for dimond python tests while running make test on master

### ISSUE THREAD

**Issue by sagar8192** [Yelp/fullerite#281]
Failed to import module: testzookeeper. Traceback (most recent call last):
  File "src/diamond/test.py", line 261, in getCollectorTests
    ['*'])
  File "/nail/home/sagarp/fullerite/src/diamond/collectors/zookeeper/test/testzookeeper.py", line 9, in <module>
    from zookeeper import ZookeeperCollector
ImportError: cannot import name ZookeeperCollector

Failed to import module: testsmart. Traceback (most recent call last):
  File "src/diamond/test.py", line 261, in getCollectorTests
    ['*'])
  File "/nail/home/sagarp/fullerite/src/diamond/collectors/smart/test/testsmart.py", line 13, in <module>
    from smart import SmartCollector
ImportError: cannot import name SmartCollector

Failed to import module: test_scribe. Traceback (most recent call last):
  File "src/diamond/test.py", line 261, in getCollectorTests
    ['*'])
  File "/nail/home/sagarp/fullerite/src/diamond/collectors/scribe/test/test_scribe.py", line 8, in <module>
    from scribe import ScribeCollector
ImportError: cannot import name ScribeCollector
...........Unable to convert 277.0xs: unit xs
.................Cannot load json data: No JSON object could be decoded: line 1 column 0 (char 0)
..........need more than 1 value to unpack
.need more than 1 value to unpack
.need more than 1 value to unpack
..............................................Unable to parse response from solr as a json object
...................................Unable to parse response from elasticsearch as a json object
....Unable to read JSON response: No JSON object could be decoded
.......Couldnt parse json: No JSON object could be decoded
........................................GearmanCollector Error:
...Couldnt parse json: No JSON object could be decoded
.....Unable to read JSON response.
Unable to retrieve MBean listing.
.....Unable to parse response from mx4j
.http://127.0.0.1:8082/path?template=identity: <urlopen error BOOM>
.......
----------------------------------------------------------------------

**Comment by gnufied** [comment]
That is okay. We are bit unsure about how to deal with remaining Diamond collector failure/errors. For now, we have simply chose to whitelist only collector tests that pass.
